CREATE TABLE customer (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   customer_code TEXT,
   name TEXT NOT NULL,
   phone TEXT,
   street TEXT,
   city TEXT,
   vat_number TEXT,
   CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE customer_contact (
  customer_contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name TEXT NOT NULL,
   last_name TEXT,
   customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   CONSTRAINT customer_contact_pkey PRIMARY KEY (customer_contact_id)
);

CREATE TABLE product (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id TEXT NOT NULL,
   description TEXT NOT NULL,
   CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE visual_inspection (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   line_comment TEXT,
   job_number INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   received_by TEXT,
   CONSTRAINT visual_inspection_pkey PRIMARY KEY (id)
);

CREATE TABLE detailed_inspection (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   inspection_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   last_updated_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   submit_by TEXT,
   CONSTRAINT detailed_inspection_pkey PRIMARY KEY (id)
);

ALTER TABLE customer ADD CONSTRAINT customer_customer_code_key UNIQUE (customer_code);

ALTER TABLE customer ADD CONSTRAINT customer_vat_number_key UNIQUE (vat_number);

CREATE TABLE inquiry (
  job_number INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   customer_contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   customer_rfq TEXT NOT NULL,
   job_category JOB_CATEGORY NOT NULL,
   CONSTRAINT inquiry_pkey PRIMARY KEY (job_number)
);

ALTER TABLE product ADD CONSTRAINT product_product_id_key UNIQUE (product_id);

ALTER TABLE inquiry ADD CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE inquiry ADD CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE inquiry ADD CONSTRAINT fk_customer_contact FOREIGN KEY (customer_contact_id) REFERENCES customer_contact (customer_contact_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE detailed_inspection ADD CONSTRAINT fk_inspection_id FOREIGN KEY (inspection_id) REFERENCES visual_inspection (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE visual_inspection ADD CONSTRAINT fk_job_number FOREIGN KEY (job_number) REFERENCES inquiry (job_number) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE visual_inspection ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE visual_inspection ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;